name: Update Fake Config

on:
  schedule:
    - cron: "0 * * * *"  # প্রতি ১ ঘণ্টা
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Copy Original to ProxyMama
        run: |
          cp original.yaml proxymama.yaml

      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add proxymama.yaml
          git commit -m "Auto update proxymama.yaml from original.yaml" || echo "No changes"
          git push
